name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Submodule
      run: git submodule update --init --recursive
    - name: Set AppID
      run: set /p APP_ID=<app_id.txt
    - name: CMake Generate
      run: cmake -B build -G "Visual Studio 16 2019" -A Win32
    - name: CMake Build
      run: 
        cmake --build build --target app --config Debug --clean-first --verbose
        cmake --build build --target app --config Release --clean-first --verbose
    - name: Pack Debug Build
      run: 
        copy build\Debug\app.dll app.dll
        7z a build\Debug\%APP_ID%.zip app.json app.dll
    - name: Pack Release Build
      run: 
        copy build\Release\app.dll app.dll
        7z a build\Release\%APP_ID%.zip app.json app.dll
      
        
